version: '3.8'

services:
  frontend-admin:
    build: ./frontadmin
    container_name: frontend-admin
    image: frontend-admin
    ports:
      - "3000:3000"
    depends_on:
      - backend-admin
   

  backend-admin:
    build: ./backadmin
    container_name: backend-admin
    image: backend-admin
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:password@db/project"
   
    
  frontend-kiosk:
    build: ./project
    container_name: frontend-kiosk
    image: frontend-kiosk
    ports:
      - "3001:3001"
  

  backend-kisosk:
    build: ./backend
    container_name: backend-kiosk
    image: backend-kiosk
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: "mysql://user:password@db/project"
  

  db:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1  # Enable to connect to arbitrary server
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db-data: {}



