version: '3'

services:
  backend:
    build: ./backend  # Path to the directory containing your Flask application Dockerfile
    ports:
      - "5000:5000"  # Expose port 5000 for Flask
    volumes:
      - ./backend:/app  # Mount the backend directory to /app in the container
    depends_on:
      - database  # If you have a database service, ensure it's started before the backend

  frontend:
    build: ./frontend  # Path to the directory containing your React application Dockerfile
    ports:
      - "3000:3000"  # Expose port 3000 for React
    volumes:
      - ./frontend:/app  # Mount the frontend directory to /app in the container
    depends_on:
      - backend  # Ensure backend is started before frontend

  database:
    image: postgres:latest  # Use the latest PostgreSQL image
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"  # Expose PostgreSQL port if needed
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persist database data
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      -"8080:80"
    depends_on:
      -db

  # Add other services if needed
